services:
  frontend:
    image: dahariyavinay/frontend:v1
    container_name: frontend
   
    ports:
      - "3000:80"       # host 3000 â†’ container 80 (nginx)
    networks:
      - clinixpro
    deploy:
      resources:
        limits:
          memory: 500m

networks:
  clinixpro:
    external: true
