services:

  h2-db:
    image: oscarfonts/h2
    container_name: h2-db
    environment:
      H2_OPTIONS: -web -webAllowOthers -tcp -tcpAllowOthers -ifNotExists -baseDir /opt/h2-data
      H2_DATABASE: clinixpro_service_offering_db
      H2_USER: vinay
      H2_PASSWORD: Vinay123@#$
    ports:
      - "2023:81"
      - "1521:1521"
    volumes:
      - /host_mnt/d/Program Files/h2-data:/opt/h2-data
    networks:
      - clinixpro

networks:
  clinixpro:
    external: true

volumes:
  h2-data:
