services:

  mysql-db:
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: clinixpro_user_db
      MYSQL_USER: vinay
      MYSQL_PASSWORD: Vinay123@#$
    ports:
      - "3306:3306"
    volumes:
      - /host_mnt/d/Program Files/mysql-data:/var/lib/mysql
    networks:
      - clinixpro

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql-db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "2021:80"
    depends_on:
      - mysql-db
    networks:
      - clinixpro

networks:
  clinixpro:
    external: true

volumes:
  mysql-data:
