server:
  port: 1019

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/vinaydahariya/clinixpro-config
          default-label: main
          clone-on-start: true
          force-pull: true
          # agar private repo hai:
          username: ${GITHUB_USERNAME}
          password: ${GITHUB_TOKEN}
          search-paths:
            - "gateway-server"
            - "user-service"
            - "clinic-service"
            - "category-service"
            - "booking-service"
            - "payment-service"
            - "notification-service"
            - "review-service"
            - "service-offering-service"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


info:
  app:
    name: "Config Server"
    description: "Config Server API For Clinic Booking System"
    version: "1.0.0"
